[build]
  publish = "staticfiles/"
  command = "python -c \"import os; os.system('sh build.sh')\""

[build.environment]
  PYTHON_VERSION = "3.10"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 